version: '3'
services:
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true   
        stdin_open: true                 
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - /c/Users/ma200/frontend:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - /c/Users/ma200/frontend:/app
        command: ["npm", "run", "test"]

