name: Simple Milestone Report

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'GitHub Owner'
        required: true
        default: 'GH-Mexico-Universidad'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Report with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.event.inputs.owner }}
      run: |
        echo "# Milestone Report for $OWNER" > report.md
        echo "Generated on: $(date)" >> report.md
        echo "" >> report.md
        
        # Crear archivo temporal para almacenar datos de milestones
        temp_file=$(mktemp)
        
        # Obtener repositorios y sus milestones
        gh repo list $OWNER --limit 100 --json name | jq -r '.[].name' | while read repo; do
          echo "Processing repository: $repo" >&2
          gh api repos/$OWNER/$repo/milestones --jq '.[] | "\(.title)|\(.state)|\(.closed_issues)|\(.open_issues + .closed_issues)|'$repo'"' >> $temp_file 2>/dev/null || true
        done
        
        # Procesar y agrupar por milestone
        if [ -s $temp_file ]; then
          # Ordenar por nombre de milestone y procesar
          sort $temp_file | awk -F'|' '
          BEGIN {
            current_milestone = ""
            print "## Milestones Summary\n"
          }
          {
            milestone = $1
            state = $2
            closed = $3
            total = $4
            repo = $5
            
            if (milestone != current_milestone) {
              if (current_milestone != "") {
                print ""
              }
              print "### " milestone
              current_milestone = milestone
            }
            
            progress = (total > 0) ? sprintf("%.1f%%", (closed/total)*100) : "0%"
            print "- **" repo "** (" state ") - " closed "/" total " issues completed (" progress ")"
          }' >> report.md
        else
          echo "No milestones found across all repositories." >> report.md
        fi
        
        # Limpiar archivo temporal
        rm -f $temp_file
        
        echo "" >> report.md
        echo "---" >> report.md
        echo "*Report generated by GitHub Actions*" >> report.md
    
    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: milestone-report-simple
        path: report.md

